# mysql:
#     image: mysql:5.7.17
#     container_name: mysql
#     volumes:
#       - ./db:/var/lib/mysql
#     environment:
#       - MYSQL_ROOT_PASSWORD='$$3cureUS'

mysql-cmdline:
    image: mysql:5.7.17
    container_name: mysql-cmdline
    external_links:
      - mysql:db
    command: bash -c "echo 'drop user '\''www'\''@'\''%'\'';create user '\''www'\''@'\''%'\'' identified by '\''$$3cureUS'\'';drop database cs4501;create database cs4501 character set utf8;grant all on cs4501.* to '\''www'\''@'\''%'\'';' > createUser.sql && cat createUser.sql && mysql -uroot -p'$$3cureUS' -h db < createUser.sql"

models:
    image: tp33/django
    container_name: isa_models
    external_links:
      -  mysql:db
    # links:
    #   - selenium:selenium
    volumes:
      - ./model_app:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py makemigrations model_app && python manage.py migrate && python manage.py loaddata ./model_app/db.json &&  mod_wsgi-express start-server --log-to-terminal --working-directory /app --reload-on-changes /app/model_app/wsgi.py"

exp:
   image: tp33/django
   container_name: isa_exp
   links:
      - models:models-api
      - kafka:kafka_container
      - es:es
      # - selenium:selenium
   ports:
      - "8002:8000"
   volumes:
      - ./exp_app:/app
   command: bash -c "mod_wsgi-express start-server --log-to-terminal --working-directory /app --reload-on-changes /app/exp_app/wsgi.py"

web:
   image: tp33/django
   container_name: isa_web
   links:
      - exp:exp-api
      - selenium:selenium
   ports:
      - "8000:8000"
   volumes:
      - ./web_app:/app
   command: bash -c "pip install selenium && mod_wsgi-express start-server --log-to-terminal --working-directory /app --reload-on-changes /app/web_app/wsgi.py"

kafka:
    image: spotify/kafka
    container_name: kafka
    environment:
        ADVERTISED_HOST: kafka
        ADVERTISED_PORT: 9092
    hostname: kafka

es:
    image: elasticsearch:2.0
    container_name: es
    volumes:
      - ./model_app:/app
    ports:
        - "9200:9200"

batch:
    image: tp33/django
    container_name: batch
    links:
        - kafka:kafka
        - es:es
    volumes:
        - ./batch:/app
    command: bash -c "python batch_script.py"

selenium:
    image: selenium/standalone-firefox:3.3.1-cesium
    container_name: selenium
    # links:
    #     - web:web-app
    ports:
        - "4444:4444"
    # environment:
    #     ADVERTISED_HOST: selenium
    #     ADVERTISED_PORT: 4444
    # hostname: selenium
    volumes:
        - ./selenium:/dev/shm

